project:
  type: website
  execute-dir: project
  output-dir: docs
  render:
    - "*.qmd"
  resources:
    - "slides/"
    - "img/"

website:
  title: "basicBayes"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: setup.qmd
        text: Set-up
      - text: Slides
        menu:
          - href: "slides/01_introduction/"
            text: "01 - Introduction"
          - href: "slides/02_brm/"
            text: "02 - BRM basics"
          - href: "slides/03_interactions/"
            text: "03 - Interactions"
          - href: "slides/04_binary/"
            text: "04 - Binary outcomes"
      - text: Tutorials
        menu:
          - href: "tutorials/tutorial_01.qmd"
            text: "Tutorial 01"
          - href: "tutorials/tutorial_02.qmd"
            text: "Tutorial 02"
          - href: "tutorials/tutorial_03.qmd"
            text: "Tutorial 03"
          - href: "tutorials/tutorial_04.qmd"
            text: "Tutorial 04"

format:
  html:
    theme: pulse
    css: styles.css
    toc: true
    df-print: paged



