project:
  type: website
  execute-dir: project
  output-dir: docs
  render:
    - "*.qmd"
  resources:
    - "slides/"
    - "img/"

website:
  title: "basicBayes"
  navbar:
    left:
      - href: index.qmd
        text: Home

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    df-print: paged



