---
title: "02 - Regression"
author: "Stefano Coretta"
---

```{r}
#| label: setup
#| include: false

library(tidyverse)
theme_set(theme_light())
library(brms)
```

## Vowel duration

```{r}
#| label: durations
#| echo: false
#| message: false

durations <- read_csv("data/coretta2018/token-measures.csv") |> 
  filter(language == "Italian")

durations
```

## Vowel durations: plot

```{r}
#| label: fig-durations
#| fig-cap: "Vowel duration and speech rate."
#| warning: false
#| echo: false

durations |> 
  ggplot(aes(speech_rate, v1_duration)) +
  geom_point(alpha = 0.5) +
  labs(
    x = "Speech rate (syl/s)", y = "Vowel duration (ms)"
  )
```

## A log-normal model of vowel duration

$$
dur \sim LogNormal(\mu, \sigma)
$$

. . . 

```{r}
#| label: dur-logn
#| eval: false

dur_logn <- brm(
  v1_duration ~ 1,
  family = lognormal,
  data = durations
)
```

. . .

::: box-error
But we want to investigate the relationship between speech rate and vowel duration!
:::

## Allow $\mu$ to vary depending on speech rate

$$
\begin{align}
dur_i & \sim LogNormal(\mu_i, \sigma)\\
\mu_i & = \beta_0 + \beta_1 \cdot SR_i\\
\end{align}
$$

. . .

::: box-tip
Does the formula for $\mu$ ring a bell?
:::

## The formula of a line

::: box-note
$$
y = a + b \cdot x
$$

- $a$ is the line's **intercept**.

- $b$ is the line's **slope** (aka gradient).

See [Linear models illustrated](https://stefanocoretta.shinyapps.io/lines/).

:::


## Regression models

```{r}
#| label: rt-phonlev

rt_phonlev <- brm(
  RT ~ 1 + PhonLev,
  family = lognormal,
  data = mald,
  cores = 4,
  seed = 1032,
  file = "data/cache/rt_phonlev"
)
```

```{r}
#| label: rt-phonlev-summary

summary(rt_phonlev)
```

```{r}
#| label: fig-rt-phonlevl-cond

conditional_effects(rt_phonlev)
```

