---
title: "04 - Count variables"
author: "Stefano Coretta"
---

```{r}
#| label: setup
#| include: false

library(tidyverse)
theme_set(theme_light())
library(brms)
library(posterior)
```

```{r}
gestures <- read_csv("data/cameron2020/gestures.csv")
gestures_12 <- gestures |> 
  filter(months == 12, count > 5)
```

```{r}
gest_pois <- brm(
  count ~ 0 + background,
  family = poisson,
  data = gestures_12,
  cores = 4,
  seed = 8712,
  file = "data/cache/gest_pois"
)
```

```{r}
pp_check(gest_pois)
```


```{r}
conditional_effects(gest_pois)
```

```{r}
gest_pois_draws <- as_draws_df(gest_pois)

gest_pois_draws
```

```{r}
gest_pois_draws <- gest_pois_draws |> 
  mutate(
    Bengali = exp(b_backgroundBengali),
    Chinese = exp(b_backgroundChinese),
    English = exp(b_backgroundEnglish)
  )

gest_pois_draws |> select(Bengali:English)
```

```{r}
gest_pois_draws |> 
  select(Bengali:English) |> 
  pivot_longer(Bengali:English, names_to = "coef", values_to = "est") |> 
  group_by(coef) |> 
  summarise(
    ci_lo = round(quantile2(est, probs = 0.025)),
    ci_hi = round(quantile2(est, probs = 0.975))
  )
```

