{
  "hash": "d3db068d4a91568449c1bd0752089a1b",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"03 - Regression models\"\nauthor: \"Stefano Coretta\"\n---\n\n\n\n## Vowel duration\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 887 × 57\n   index speaker file     rec_date        ipu   prompt word    time sentence_ons\n   <dbl> <chr>   <chr>    <chr>           <chr> <chr>  <chr>  <dbl>        <dbl>\n 1     1 it01    it01-001 29/11/2016 15:… ipu_1 Dico … pugu   0.990        0.990\n 2     2 it01    it01-002 29/11/2016 15:… ipu_2 Dico … pada   3.62         0.502\n 3     3 it01    it01-003 29/11/2016 15:… ipu_3 Dico … poco   6.13         0.697\n 4     4 it01    it01-004 29/11/2016 15:… ipu_4 Dico … pata   8.82         0.623\n 5     5 it01    it01-005 29/11/2016 15:… ipu_5 Dico … boco  11.5          0.665\n 6     6 it01    it01-006 29/11/2016 15:… ipu_6 Dico … podo  14.3          0.647\n 7     7 it01    it01-007 29/11/2016 15:… ipu_7 Dico … boto  17.2          0.740\n 8     8 it01    it01-008 29/11/2016 15:… ipu_8 Dico … paca  19.7          0.502\n 9     9 it01    it01-009 29/11/2016 15:… ipu_9 Dico … bodo  22.3          0.556\n10    10 it01    it01-010 29/11/2016 15:… ipu_… Dico … pucu  24.8          0.535\n# ℹ 877 more rows\n# ℹ 48 more variables: sentence_off <dbl>, word_ons <dbl>, word_off <dbl>,\n#   v1_ons <dbl>, c2_ons <dbl>, v2_ons <dbl>, c1_rel <dbl>, c2_rel <dbl>,\n#   voicing_start <dbl>, voicing_end <dbl>, voicing_duration <dbl>,\n#   voiced_points <dbl>, GONS <dbl>, max <dbl>, NOFF <dbl>, NONS <dbl>,\n#   peak1 <dbl>, peak2 <dbl>, c1_duration <dbl>, c1_clos_duration <dbl>,\n#   c1_vot <dbl>, c1_rvoff <dbl>, v1_duration <dbl>, c2_duration <dbl>, …\n```\n\n\n:::\n:::\n\n\n## Vowel durations: plot\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Vowel duration and speech rate.](03-regression_files/figure-revealjs/fig-durations-1.png){#fig-durations width=960}\n:::\n:::\n\n\n## A log-normal model of vowel duration\n\n$$\ndur \\sim LogNormal(\\mu, \\sigma)\n$$\n\n. . . \n\n\n::: {.cell}\n\n```{.r .cell-code}\ndur_logn <- brm(\n  v1_duration ~ 1,\n  family = lognormal,\n  data = durations\n)\n```\n:::\n\n\n. . .\n\n::: box-error\nBut we want to investigate the relationship between speech rate and vowel duration!\n:::\n\n## Allow $\\mu$ to vary depending on speech rate\n\n$$\n\\begin{align}\ndur_i & \\sim LogNormal(\\mu_i, \\sigma)\\\\\n\\mu_i & = \\beta_0 + \\beta_1 \\cdot SR_i\\\\\n\\end{align}\n$$\n\n. . .\n\n::: box-tip\nDoes the formula for $\\mu$ ring a bell?\n:::\n\n## The formula of a line\n\n::: box-note\n$$\ny = a + b \\cdot x\n$$\n\n- $a$ is the line's **intercept**. This is $y$ when $x$ is 0.\n\n- $b$ is the line's **slope** (aka gradient). This is the change in $y$ for every unit increase of $x$.\n\nSee [Linear models illustrated](https://stefanocoretta.shinyapps.io/lines/).\n\n:::\n\n## Regression model of vowel duration\n\n$$\n\\begin{align}\ndur_i & \\sim LogNormal(\\mu_i, \\sigma)\\\\\n\\mu_i & = \\beta_0 + \\beta_1 \\cdot SR_i\\\\\n\\end{align}\n$$\n\n::: box-note\n- $\\beta_0$ is the intercept. This is the mean vowel duration when speech rate is 0.\n\n- $\\beta_1$ is the slope. This is the change in vowel duration for each unit increase of speech rate (syl/s).\n:::\n\n## But...\n\n::: box-warning\n**Speech rate 0 doesn't make sense!**\n\n- Speech rate cannot be zero syllables per second.\n:::\n\n. . .\n\n::: box-tip\nWe can **centre** speech rate.\n\n- Subtract the mean speech rate from all the speech rate values.\n:::\n\n## Centred speech rate\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmean(durations$speech_rate, na.rm = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 5.314752\n```\n\n\n:::\n\n```{.r .cell-code}\ndurations <- durations |> \n  mutate(\n    speech_rate_c = speech_rate - mean(speech_rate, na.rm = TRUE)\n  )\n```\n:::\n\n\n::: box-note\n- `speach_rate_c` = 0 means mean speech rate. \n:::\n\n## Centred speech rate: plot\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Vowel duration and (centred) speech rate.](03-regression_files/figure-revealjs/fig-durations-centred-1.png){#fig-durations-centred width=960}\n:::\n:::\n\n\n## Regression model of vowel durations: centred speech rate\n\n$$\n\\begin{align}\ndur_i & \\sim LogNormal(\\mu_i, \\sigma)\\\\\n\\mu_i & = \\beta_0 + \\beta_1 \\cdot SR_{ctr[i]}\\\\\n\\end{align}\n$$\n\n::: box-note\n- $\\beta_0$ is the intercept. This is the mean RT when centred speech rate is 0 (i.e. when speech rate is at its mean = NA).\n\n- $\\beta_1$ is the slope. This is the change in RT for each unit increase of centred speech rate (i.e for every unit increase of speech rate).\n:::\n\n## Regression model of vowel durations: code\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndur_sr <- brm(\n  v1_duration ~ 1 + speech_rate_c,\n  family = lognormal,\n  data = durations,\n  cores = 4,\n  seed = 1032,\n  file = \"data/cache/dur_sr\"\n)\n```\n:::\n\n\n## Regression model: summary\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(dur_sr)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n Family: lognormal \n  Links: mu = identity; sigma = identity \nFormula: v1_duration ~ 1 + speech_rate_c \n   Data: durations (Number of observations: 886) \n  Draws: 4 chains, each with iter = 2000; warmup = 1000; thin = 1;\n         total post-warmup draws = 4000\n\nRegression Coefficients:\n              Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS\nIntercept         4.72      0.01     4.71     4.74 1.00     4388     2452\nspeech_rate_c    -0.23      0.01    -0.25    -0.22 1.00     4482     2982\n\nFurther Distributional Parameters:\n      Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS\nsigma     0.22      0.01     0.21     0.23 1.00     3913     2983\n\nDraws were sampled using sampling(NUTS). For each parameter, Bulk_ESS\nand Tail_ESS are effective sample size measures, and Rhat is the potential\nscale reduction factor on split chains (at convergence, Rhat = 1).\n```\n\n\n:::\n:::\n\n\n## Interpreting the summary\n\n$$\n\\begin{align}\ndur_i & \\sim LogNormal(\\mu_i, \\sigma)\\\\\n\\mu_i & = \\beta_0 + \\beta_1 \\cdot SR_{ctr[i]}\\\\\n\\end{align}\n$$\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfixef(dur_sr)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                Estimate   Est.Error       Q2.5      Q97.5\nIntercept      4.7230357 0.007580906  4.7081901  4.7379128\nspeech_rate_c -0.2344362 0.009378120 -0.2525304 -0.2157794\n```\n\n\n:::\n:::\n\n\n::: box-note\n- `Intercept` is $\\beta_0$: mean duration when speech rate is at mean.\n\n- `speech_rate_c` is $\\beta_1$: change in duration for each unit increase of speech rate.\n:::\n\n## Interpreting the summary: `Intercept`\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfixef(dur_sr)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                Estimate   Est.Error       Q2.5      Q97.5\nIntercept      4.7230357 0.007580906  4.7081901  4.7379128\nspeech_rate_c -0.2344362 0.009378120 -0.2525304 -0.2157794\n```\n\n\n:::\n:::\n\n\n::: box-note\n- The mean logged vowel duration is on average 4.72 (SD = 0.008).\n\n- There is a 95% probability that the mean logged vowel duration is between 4.71 and 4.74.\n:::\n\n## Interpreting the summary: `speech_rate_c`\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfixef(dur_sr)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                Estimate   Est.Error       Q2.5      Q97.5\nIntercept      4.7230357 0.007580906  4.7081901  4.7379128\nspeech_rate_c -0.2344362 0.009378120 -0.2525304 -0.2157794\n```\n\n\n:::\n:::\n\n\n::: box-note\n- The average change in logged vowel duration for each unit increase of speech rate is -0.23 (SD = 0.01).\n\n- In other words, for each increase of one syllable per second, the logged vowel duration decreases on average by -0.23.\n\n- We can be 95% confident that the decrease in logged duration is between -0.22 and -0.25.\n:::\n\n## Plotting the model predictions\n\n\n::: {.cell}\n\n```{.r .cell-code}\nconditional_effects(dur_sr)\n```\n\n::: {.cell-output-display}\n![](03-regression_files/figure-revealjs/fig-dur-sr-cond-1.png){#fig-dur-sr-cond width=960}\n:::\n:::\n\n\n## Posterior predictive checks\n\n\n::: {.cell}\n\n```{.r .cell-code}\npp_check(dur_sr, ndraws = 20)\n```\n\n::: {.cell-output-display}\n![Posterior predictive check plot of `dur_sr`.](03-regression_files/figure-revealjs/fig-dur-sr-pp-1.png){#fig-dur-sr-pp width=960}\n:::\n:::\n\n\n## Summary\n\n::: box-tip\n- Regression models are models that use the formula of a line.\n\n- A simple regression model with one numeric predictor estimates the line's intercept ($beta_0$) and slope ($beta_1$) and the overall standard deviation ($sigma$).\n\n$$\n\\begin{align}\ny_i & \\sim LogNormal(\\mu_i, \\sigma)\\\\\n\\mu_i & = \\beta_0 + \\beta_1 \\cdot x\n\\end{align}\n$$\n:::\n",
    "supporting": [
      "03-regression_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}