---
title: "Tutorial 04: Diagnostics"
execute: 
  cache: true
---

```{r}
#| label: pkgs
#| message: false
#| echo: false

library(tidyverse)
theme_set(theme_light())

library(brms)

polite <- read_csv("data/polite.csv") %>%
  drop_na()
```

## Diagnostics

There are many ways to check for model robustness (the concept of "robustness" is not a mathematical one, so you can use a bunch of heuristics to assess robustness).

Go back to the models you fitted in the tutorials 1-3 and check them with the following methods:

- Use `plot()` to have a look at the chain plots. Do they look like "hairy caterpillars"?

- Plot the cumulative posterior distribution with `pp_check()`. Do the simulated posteriors (in light blue) look like the empirical distribution (in dark blue)?

- Check the $\hat{R}$ values using `summary()`. Are they close to one? Did you get any warnings regarding $\hat{R}$ or ESS?

## Challenge

If you feel like it and have time, try and run other models either using the data provided or with your own data if you have some.

I'll be happy to answer your questions!
